version: "3.9"
services:
  db:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - dbdata:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - backend

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - users
      - products
    networks:
      - backend

  users:
    build: ./services/users
    ports:
      - "8001:8001"
    networks:
      - backend
    depends_on:
      - db

  products:
    build: ./services/products
    ports:
      - "8002:8002"
    networks:
      - backend
    depends_on:
      - db
      - users

volumes:
  dbdata:

networks:
  backend:
    driver: bridge
